### ISSUE TITLE
wn is not defined 

### ISSUE THREAD

**Issue by mehrdadmms** [pouriaMaleki/eghtesad-novin-checkout#2]
Hi 
I'm trying to connect to novin pardakht with your package but I get this error 
It seems like "wn" is not defined 
What is "wn" ? 
I'm not familiar with LiveScript I'm trying to use your package with NodeJs (version 10.16.2) 

> ReferenceError: wn is not defined
    at module.exports (F:\projects\neolyze_current\back-end\node_modules\eghtesad-novin-checkout\lib\rc\sign.js:7:5)
    at F:\projects\neolyze_current\back-end\node_modules\eghtesad-novin-checkout\lib\rc\index.js:181:18

**Comment by pouriaMaleki** [comment]
Hi, there was a problem with the dependencies, should be fixed now.
